update cluster detach senario
identitatem/idp-mgmt-docs pull request #42
Opened 2022-01-09 23:38 UTC by leena-jawale

Signed-off-by: Leena Jawale <ljawale@redhat.com>

2022-01-09 23:40 UTC, leena-jawale commented
/cc @robinbobbitt

2022-01-10 16:25 UTC, robinbobbitt requested changes

2022-01-10 16:25 UTC, robinbobbitt commented on quick_start.adoc
> +Before detaching cluster from hub, copy original OAuth from the ConfigMap named `idp-oauth-original` in the managed cluster's namespace on the hub cluster. After cluster is completely detached from h
I think we need to handle this with two PRs.. One for now before your change that orphans the IDP Oauth config goes live, and another one that we hold until then with the info you provide above (or tell them to take it out of management before detaching it, and if they didn't, then follow your guidance). For now, we need to add an `IMPORTANT` note that they need to make sure the cluster is no longer under IDP config management before detaching it (by making sure it doesn't match the placement... remove labels or remove from managed cluster set) or they will lose access to the cluster. I think this should probably be up in the section about adding clusters to the managed cluster set, or at least be separated from this RBAC note into its own `IMPORTANT` section.

2022-01-10 17:26 UTC, leena-jawale commented
/hold
Until release

2022-01-20 21:19 UTC, robinbobbitt commented on quick_start.adoc
> +Before detaching cluster from hub, copy original OAuth from the ConfigMap named `idp-oauth-original` in the managed cluster's namespace on the hub cluster. After cluster is completely detached from h
@leena-jawale please see https://github.com/identitatem/idp-mgmt-docs-upstream/pull/2

2022-01-20 21:20 UTC, robinbobbitt commented
Closing as we are now making changes to the upstream repo. Recommended changes are here: https://github.com/identitatem/idp-mgmt-docs-upstream/pull/2

2022-01-20 21:20 UTC, closed without merging